// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: record.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_record_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_record_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021005 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_record_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_record_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_record_2eproto;
class Company;
struct CompanyDefaultTypeInternal;
extern CompanyDefaultTypeInternal _Company_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::Company* Arena::CreateMaybeMessage<::Company>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class Company final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Company) */ {
 public:
  inline Company() : Company(nullptr) {}
  ~Company() override;
  explicit PROTOBUF_CONSTEXPR Company(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Company(const Company& from);
  Company(Company&& from) noexcept
    : Company() {
    *this = ::std::move(from);
  }

  inline Company& operator=(const Company& from) {
    CopyFrom(from);
    return *this;
  }
  inline Company& operator=(Company&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Company& default_instance() {
    return *internal_default_instance();
  }
  static inline const Company* internal_default_instance() {
    return reinterpret_cast<const Company*>(
               &_Company_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Company& a, Company& b) {
    a.Swap(&b);
  }
  inline void Swap(Company* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Company* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Company* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Company>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Company& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Company& from) {
    Company::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Company* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Company";
  }
  protected:
  explicit Company(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
    kYearOfFoundationFieldNumber = 2,
    kAdressFieldNumber = 3,
    kTypeOfActivityFieldNumber = 4,
    kInternationalActivityFieldNumber = 5,
  };
  // required string name = 1;
  bool has_name() const;
  private:
  bool _internal_has_name() const;
  public:
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // required string year_of_foundation = 2;
  bool has_year_of_foundation() const;
  private:
  bool _internal_has_year_of_foundation() const;
  public:
  void clear_year_of_foundation();
  const std::string& year_of_foundation() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_year_of_foundation(ArgT0&& arg0, ArgT... args);
  std::string* mutable_year_of_foundation();
  PROTOBUF_NODISCARD std::string* release_year_of_foundation();
  void set_allocated_year_of_foundation(std::string* year_of_foundation);
  private:
  const std::string& _internal_year_of_foundation() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_year_of_foundation(const std::string& value);
  std::string* _internal_mutable_year_of_foundation();
  public:

  // required string adress = 3;
  bool has_adress() const;
  private:
  bool _internal_has_adress() const;
  public:
  void clear_adress();
  const std::string& adress() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_adress(ArgT0&& arg0, ArgT... args);
  std::string* mutable_adress();
  PROTOBUF_NODISCARD std::string* release_adress();
  void set_allocated_adress(std::string* adress);
  private:
  const std::string& _internal_adress() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_adress(const std::string& value);
  std::string* _internal_mutable_adress();
  public:

  // optional string type_of_activity = 4;
  bool has_type_of_activity() const;
  private:
  bool _internal_has_type_of_activity() const;
  public:
  void clear_type_of_activity();
  const std::string& type_of_activity() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_type_of_activity(ArgT0&& arg0, ArgT... args);
  std::string* mutable_type_of_activity();
  PROTOBUF_NODISCARD std::string* release_type_of_activity();
  void set_allocated_type_of_activity(std::string* type_of_activity);
  private:
  const std::string& _internal_type_of_activity() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_type_of_activity(const std::string& value);
  std::string* _internal_mutable_type_of_activity();
  public:

  // optional bool international_activity = 5;
  bool has_international_activity() const;
  private:
  bool _internal_has_international_activity() const;
  public:
  void clear_international_activity();
  bool international_activity() const;
  void set_international_activity(bool value);
  private:
  bool _internal_international_activity() const;
  void _internal_set_international_activity(bool value);
  public:

  // @@protoc_insertion_point(class_scope:Company)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr year_of_foundation_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr adress_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr type_of_activity_;
    bool international_activity_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_record_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Company

// required string name = 1;
inline bool Company::_internal_has_name() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Company::has_name() const {
  return _internal_has_name();
}
inline void Company::clear_name() {
  _impl_.name_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Company::name() const {
  // @@protoc_insertion_point(field_get:Company.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Company::set_name(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000001u;
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Company.name)
}
inline std::string* Company::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:Company.name)
  return _s;
}
inline const std::string& Company::_internal_name() const {
  return _impl_.name_.Get();
}
inline void Company::_internal_set_name(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* Company::_internal_mutable_name() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* Company::release_name() {
  // @@protoc_insertion_point(field_release:Company.name)
  if (!_internal_has_name()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* p = _impl_.name_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void Company::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Company.name)
}

// required string year_of_foundation = 2;
inline bool Company::_internal_has_year_of_foundation() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool Company::has_year_of_foundation() const {
  return _internal_has_year_of_foundation();
}
inline void Company::clear_year_of_foundation() {
  _impl_.year_of_foundation_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& Company::year_of_foundation() const {
  // @@protoc_insertion_point(field_get:Company.year_of_foundation)
  return _internal_year_of_foundation();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Company::set_year_of_foundation(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000002u;
 _impl_.year_of_foundation_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Company.year_of_foundation)
}
inline std::string* Company::mutable_year_of_foundation() {
  std::string* _s = _internal_mutable_year_of_foundation();
  // @@protoc_insertion_point(field_mutable:Company.year_of_foundation)
  return _s;
}
inline const std::string& Company::_internal_year_of_foundation() const {
  return _impl_.year_of_foundation_.Get();
}
inline void Company::_internal_set_year_of_foundation(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.year_of_foundation_.Set(value, GetArenaForAllocation());
}
inline std::string* Company::_internal_mutable_year_of_foundation() {
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.year_of_foundation_.Mutable(GetArenaForAllocation());
}
inline std::string* Company::release_year_of_foundation() {
  // @@protoc_insertion_point(field_release:Company.year_of_foundation)
  if (!_internal_has_year_of_foundation()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* p = _impl_.year_of_foundation_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.year_of_foundation_.IsDefault()) {
    _impl_.year_of_foundation_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void Company::set_allocated_year_of_foundation(std::string* year_of_foundation) {
  if (year_of_foundation != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.year_of_foundation_.SetAllocated(year_of_foundation, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.year_of_foundation_.IsDefault()) {
    _impl_.year_of_foundation_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Company.year_of_foundation)
}

// required string adress = 3;
inline bool Company::_internal_has_adress() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool Company::has_adress() const {
  return _internal_has_adress();
}
inline void Company::clear_adress() {
  _impl_.adress_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const std::string& Company::adress() const {
  // @@protoc_insertion_point(field_get:Company.adress)
  return _internal_adress();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Company::set_adress(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000004u;
 _impl_.adress_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Company.adress)
}
inline std::string* Company::mutable_adress() {
  std::string* _s = _internal_mutable_adress();
  // @@protoc_insertion_point(field_mutable:Company.adress)
  return _s;
}
inline const std::string& Company::_internal_adress() const {
  return _impl_.adress_.Get();
}
inline void Company::_internal_set_adress(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.adress_.Set(value, GetArenaForAllocation());
}
inline std::string* Company::_internal_mutable_adress() {
  _impl_._has_bits_[0] |= 0x00000004u;
  return _impl_.adress_.Mutable(GetArenaForAllocation());
}
inline std::string* Company::release_adress() {
  // @@protoc_insertion_point(field_release:Company.adress)
  if (!_internal_has_adress()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004u;
  auto* p = _impl_.adress_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.adress_.IsDefault()) {
    _impl_.adress_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void Company::set_allocated_adress(std::string* adress) {
  if (adress != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.adress_.SetAllocated(adress, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.adress_.IsDefault()) {
    _impl_.adress_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Company.adress)
}

// optional string type_of_activity = 4;
inline bool Company::_internal_has_type_of_activity() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool Company::has_type_of_activity() const {
  return _internal_has_type_of_activity();
}
inline void Company::clear_type_of_activity() {
  _impl_.type_of_activity_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline const std::string& Company::type_of_activity() const {
  // @@protoc_insertion_point(field_get:Company.type_of_activity)
  return _internal_type_of_activity();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Company::set_type_of_activity(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000008u;
 _impl_.type_of_activity_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Company.type_of_activity)
}
inline std::string* Company::mutable_type_of_activity() {
  std::string* _s = _internal_mutable_type_of_activity();
  // @@protoc_insertion_point(field_mutable:Company.type_of_activity)
  return _s;
}
inline const std::string& Company::_internal_type_of_activity() const {
  return _impl_.type_of_activity_.Get();
}
inline void Company::_internal_set_type_of_activity(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.type_of_activity_.Set(value, GetArenaForAllocation());
}
inline std::string* Company::_internal_mutable_type_of_activity() {
  _impl_._has_bits_[0] |= 0x00000008u;
  return _impl_.type_of_activity_.Mutable(GetArenaForAllocation());
}
inline std::string* Company::release_type_of_activity() {
  // @@protoc_insertion_point(field_release:Company.type_of_activity)
  if (!_internal_has_type_of_activity()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000008u;
  auto* p = _impl_.type_of_activity_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.type_of_activity_.IsDefault()) {
    _impl_.type_of_activity_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void Company::set_allocated_type_of_activity(std::string* type_of_activity) {
  if (type_of_activity != nullptr) {
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }
  _impl_.type_of_activity_.SetAllocated(type_of_activity, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.type_of_activity_.IsDefault()) {
    _impl_.type_of_activity_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Company.type_of_activity)
}

// optional bool international_activity = 5;
inline bool Company::_internal_has_international_activity() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool Company::has_international_activity() const {
  return _internal_has_international_activity();
}
inline void Company::clear_international_activity() {
  _impl_.international_activity_ = false;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline bool Company::_internal_international_activity() const {
  return _impl_.international_activity_;
}
inline bool Company::international_activity() const {
  // @@protoc_insertion_point(field_get:Company.international_activity)
  return _internal_international_activity();
}
inline void Company::_internal_set_international_activity(bool value) {
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.international_activity_ = value;
}
inline void Company::set_international_activity(bool value) {
  _internal_set_international_activity(value);
  // @@protoc_insertion_point(field_set:Company.international_activity)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_record_2eproto
